# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator
from qiskit.visualization import plot_histogram
import matplotlib.pyplot as plt

# Create circuit (2 qubits, 2 classical bits)
qc = QuantumCircuit(2,2)

# Step 1: Superposition
qc.h(0)
qc.h(1)

# Step 2: Oracle (mark |11>)
qc.cz(0,1)

# Step 3: Diffusion operator
qc.h([0,1])
qc.x([0,1])
qc.h(1)
qc.cx(0,1)
qc.h(1)
qc.x([0,1])
qc.h([0,1])

# Step 4: Measurement
qc.measure([0,1],[0,1])

# Run simulator
simulator = AerSimulator()
job = simulator.run(qc, shots=1024)
result = job.result()

counts = result.get_counts()

print("Result:", counts)

# Plot result
plot_histogram(counts)
plt.show()